version: '3.8'

services:
  react-app:
    build: ./frontend
    ports:
      - 3000:3000
    image: phoebesu1025/mission5-frontend

  backend:
    build: ./backend
    ports:
      - 5000:5000
    image: phoebesu1025/mission5-backend

    environment:
      DB-URL: mongodb://db/geeksOnMission
      

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - M5:/data/db
volumes:
  M5:

